
cols_metadata <- readr::cols(
  accession = readr::col_character(),
  ambiguous_bases = readr::col_character(),
  checkm_completeness = readr::col_character(),
  checkm_contamination = readr::col_character(),
  checkm_marker_count = readr::col_character(),
  checkm_marker_lineage = readr::col_character(),
  checkm_marker_set_count = readr::col_character(),
  checkm_strain_heterogeneity = readr::col_character(),
  coding_bases = readr::col_character(),
  coding_density = readr::col_character(),
  contig_count = readr::col_character(),
  gc_count = readr::col_character(),
  gc_percentage = readr::col_character(),
  genome_size = readr::col_character(),
  gtdb_genome_representative = readr::col_character(),
  gtdb_representative = readr::col_character(),
  gtdb_taxonomy = readr::col_character(),
  gtdb_type_designation_ncbi_taxa = readr::col_character(),
  gtdb_type_designation_ncbi_taxa_sources = readr::col_character(),
  gtdb_type_species_of_genus = readr::col_character(),
  l50_contigs = readr::col_character(),
  l50_scaffolds = readr::col_character(),
  longest_contig = readr::col_character(),
  longest_scaffold = readr::col_character(),
  lsu_23s_contig_len = readr::col_character(),
  lsu_23s_count = readr::col_character(),
  lsu_23s_length = readr::col_character(),
  lsu_23s_query_id = readr::col_character(),
  lsu_5s_contig_len = readr::col_character(),
  lsu_5s_count = readr::col_character(),
  lsu_5s_length = readr::col_character(),
  lsu_5s_query_id = readr::col_character(),
  lsu_silva_23s_blast_align_len = readr::col_character(),
  lsu_silva_23s_blast_bitscore = readr::col_character(),
  lsu_silva_23s_blast_evalue = readr::col_character(),
  lsu_silva_23s_blast_perc_identity = readr::col_character(),
  lsu_silva_23s_blast_subject_id = readr::col_character(),
  lsu_silva_23s_taxonomy = readr::col_character(),
  mean_contig_length = readr::col_character(),
  mean_scaffold_length = readr::col_character(),
  mimag_high_quality = readr::col_character(),
  mimag_low_quality = readr::col_character(),
  mimag_medium_quality = readr::col_character(),
  n50_contigs = readr::col_character(),
  n50_scaffolds = readr::col_character(),
  ncbi_assembly_level = readr::col_character(),
  ncbi_assembly_name = readr::col_character(),
  ncbi_assembly_type = readr::col_character(),
  ncbi_bioproject = readr::col_character(),
  ncbi_biosample = readr::col_character(),
  ncbi_contig_count = readr::col_character(),
  ncbi_contig_n50 = readr::col_character(),
  ncbi_country = readr::col_character(),
  ncbi_date = readr::col_character(),
  ncbi_genbank_assembly_accession = readr::col_character(),
  ncbi_genome_category = readr::col_character(),
  ncbi_genome_representation = readr::col_character(),
  ncbi_isolate = readr::col_character(),
  ncbi_isolation_source = readr::col_character(),
  ncbi_lat_lon = readr::col_character(),
  ncbi_molecule_count = readr::col_character(),
  ncbi_ncrna_count = readr::col_character(),
  ncbi_organism_name = readr::col_character(),
  ncbi_protein_count = readr::col_character(),
  ncbi_refseq_category = readr::col_character(),
  ncbi_rrna_count = readr::col_character(),
  ncbi_scaffold_count = readr::col_character(),
  ncbi_scaffold_l50 = readr::col_character(),
  ncbi_scaffold_n50 = readr::col_character(),
  ncbi_scaffold_n75 = readr::col_character(),
  ncbi_scaffold_n90 = readr::col_character(),
  ncbi_seq_rel_date = readr::col_character(),
  ncbi_spanned_gaps = readr::col_character(),
  ncbi_species_taxid = readr::col_character(),
  ncbi_ssu_count = readr::col_character(),
  ncbi_strain_identifiers = readr::col_character(),
  ncbi_submitter = readr::col_character(),
  ncbi_taxid = readr::col_character(),
  ncbi_taxonomy = readr::col_character(),
  ncbi_taxonomy_unfiltered = readr::col_character(),
  ncbi_total_gap_length = readr::col_character(),
  ncbi_total_length = readr::col_character(),
  ncbi_translation_table = readr::col_character(),
  ncbi_trna_count = readr::col_character(),
  ncbi_type_material_designation = readr::col_character(),
  ncbi_ungapped_length = readr::col_character(),
  ncbi_unspanned_gaps = readr::col_character(),
  ncbi_wgs_master = readr::col_character(),
  protein_count = readr::col_character(),
  scaffold_count = readr::col_character(),
  ssu_contig_len = readr::col_character(),
  ssu_count = readr::col_character(),
  ssu_gg_blast_align_len = readr::col_character(),
  ssu_gg_blast_bitscore = readr::col_character(),
  ssu_gg_blast_evalue = readr::col_character(),
  ssu_gg_blast_perc_identity = readr::col_character(),
  ssu_gg_blast_subject_id = readr::col_character(),
  ssu_gg_taxonomy = readr::col_character(),
  ssu_length = readr::col_character(),
  ssu_query_id = readr::col_character(),
  ssu_silva_blast_align_len = readr::col_character(),
  ssu_silva_blast_bitscore = readr::col_character(),
  ssu_silva_blast_evalue = readr::col_character(),
  ssu_silva_blast_perc_identity = readr::col_character(),
  ssu_silva_blast_subject_id = readr::col_character(),
  ssu_silva_taxonomy = readr::col_character(),
  total_gap_length = readr::col_character(),
  trna_aa_count = readr::col_character(),
  trna_count = readr::col_character(),
  trna_selenocysteine_count = readr::col_character()
)

#' Read GTDB metadata files
#' @param file A path to a file.
#' @return A [tibble::tibble()].
#' @export
read_metadata <- function(file) {
  cols <- cols_metadata
  out <- readr::read_csv(file, col_names = names(cols$cols), col_types = cols,
                         progress = FALSE, skip = 1)
  out
}
